# Generated by Django 4.0.8 on 2022-11-29 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=50, null=True)),
                ('region', models.CharField(max_length=50, null=True)),
                ('level', models.CharField(max_length=50, null=True)),
                ('tier', models.CharField(max_length=50, null=True)),
                ('rank', models.CharField(max_length=50, null=True)),
                ('win', models.CharField(max_length=50, null=True)),
                ('lose', models.CharField(max_length=50, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champ', models.CharField(max_length=50, null=True)),
                ('kda', models.CharField(max_length=50, null=True)),
                ('total_gold', models.IntegerField(null=True)),
                ('solo_kill', models.IntegerField(null=True)),
                ('level', models.IntegerField(null=True)),
                ('cs', models.IntegerField(null=True)),
                ('match_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='users.matchdata')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='users.profile')),
            ],
        ),
    ]
