# Generated by Django 4.0.8 on 2023-01-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_matchdata_profile_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='p_region',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
